#pragma once

#include <d2d1.h>
#include <d2d1_1helper.h>
#include <dwrite.h>
#include <Wincodec.h>
#include <Windows.h>
#include <windowsx.h>
#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cwctype>
#include <functional>
#include <map>
#include <memory>
#include <algorithm>
#include <set>
#include <string>
#include <system_error>
#include <tuple>
#include <type_traits>
#include <vector>