#pragma once

#include <zaf/base/string/string_const.h>

namespace zaf {
namespace property {

ZAF_DEFINE_STRING_CONST(A);
ZAF_DEFINE_STRING_CONST(All);
ZAF_DEFINE_STRING_CONST(ARGB);
ZAF_DEFINE_STRING_CONST(B);
ZAF_DEFINE_STRING_CONST(BackgroundColor);
ZAF_DEFINE_STRING_CONST(BackgroundColorPicker);
ZAF_DEFINE_STRING_CONST(Border);
ZAF_DEFINE_STRING_CONST(BorderColor);
ZAF_DEFINE_STRING_CONST(BorderColorPicker);
ZAF_DEFINE_STRING_CONST(Bottom);
ZAF_DEFINE_STRING_CONST(BoxBackgroundColor);
ZAF_DEFINE_STRING_CONST(BoxBackgroundColorPicker);
ZAF_DEFINE_STRING_CONST(BoxBorderColor);
ZAF_DEFINE_STRING_CONST(BoxBorderColorPicker);
ZAF_DEFINE_STRING_CONST(CanAutoChangeCheckState);
ZAF_DEFINE_STRING_CONST(CanAutoSelect);
ZAF_DEFINE_STRING_CONST(CanBeIndeterminate);
ZAF_DEFINE_STRING_CONST(CanFocused);
ZAF_DEFINE_STRING_CONST(CanTabStop);
ZAF_DEFINE_STRING_CONST(CheckState);
ZAF_DEFINE_STRING_CONST(Children);
ZAF_DEFINE_STRING_CONST(Color);
ZAF_DEFINE_STRING_CONST(DefaultFont);
ZAF_DEFINE_STRING_CONST(DefaultTextColor);
ZAF_DEFINE_STRING_CONST(DefaultTextColorPicker);
ZAF_DEFINE_STRING_CONST(Delimiter);
ZAF_DEFINE_STRING_CONST(DelimiterCount);
ZAF_DEFINE_STRING_CONST(DropDownButtonColor);
ZAF_DEFINE_STRING_CONST(DropDownButtonColorPicker);
ZAF_DEFINE_STRING_CONST(DropDownButtonWidth);
ZAF_DEFINE_STRING_CONST(DropDownListBox);
ZAF_DEFINE_STRING_CONST(EditTextBox);
ZAF_DEFINE_STRING_CONST(FamilyName);
ZAF_DEFINE_STRING_CONST(G);
ZAF_DEFINE_STRING_CONST(Granularity);
ZAF_DEFINE_STRING_CONST(Height);
ZAF_DEFINE_STRING_CONST(IsChecked);
ZAF_DEFINE_STRING_CONST(IsEditable);
ZAF_DEFINE_STRING_CONST(IsEnabled);
ZAF_DEFINE_STRING_CONST(IsSelected);
ZAF_DEFINE_STRING_CONST(IsVisible);
ZAF_DEFINE_STRING_CONST(Items);
ZAF_DEFINE_STRING_CONST(ItemHeight);
ZAF_DEFINE_STRING_CONST(Left);
ZAF_DEFINE_STRING_CONST(MaximumHeight);
ZAF_DEFINE_STRING_CONST(MaximumVisibleItemCount);
ZAF_DEFINE_STRING_CONST(MaximumWidth);
ZAF_DEFINE_STRING_CONST(MinimumHeight);
ZAF_DEFINE_STRING_CONST(MinimumVisibleItemCount);
ZAF_DEFINE_STRING_CONST(MinimumWidth);
ZAF_DEFINE_STRING_CONST(Name);
ZAF_DEFINE_STRING_CONST(Padding);
ZAF_DEFINE_STRING_CONST(ParagraphAlignment);
ZAF_DEFINE_STRING_CONST(Position);
ZAF_DEFINE_STRING_CONST(R);
ZAF_DEFINE_STRING_CONST(RadioBackgroundColor);
ZAF_DEFINE_STRING_CONST(RadioBackgroundColorPicker);
ZAF_DEFINE_STRING_CONST(RadioBorderColor);
ZAF_DEFINE_STRING_CONST(RadioBorderColorPicker);
ZAF_DEFINE_STRING_CONST(Rect);
ZAF_DEFINE_STRING_CONST(Right);
ZAF_DEFINE_STRING_CONST(SelectionMode);
ZAF_DEFINE_STRING_CONST(Size);
ZAF_DEFINE_STRING_CONST(TabIndex);
ZAF_DEFINE_STRING_CONST(Text);
ZAF_DEFINE_STRING_CONST(TextAlignment);
ZAF_DEFINE_STRING_CONST(TextTrimming);
ZAF_DEFINE_STRING_CONST(Top);
ZAF_DEFINE_STRING_CONST(Type);
ZAF_DEFINE_STRING_CONST(Weight);
ZAF_DEFINE_STRING_CONST(Width);
ZAF_DEFINE_STRING_CONST(WordWrapping);
ZAF_DEFINE_STRING_CONST(X);
ZAF_DEFINE_STRING_CONST(XRadius);
ZAF_DEFINE_STRING_CONST(Y);
ZAF_DEFINE_STRING_CONST(YRadius);

}
}