#pragma once

#include <zaf/base/string/string_const.h>

namespace zaf {
namespace type {

ZAF_DEFINE_STRING_CONST(Button);
ZAF_DEFINE_STRING_CONST(CheckBox);
ZAF_DEFINE_STRING_CONST(ClickableControl);
ZAF_DEFINE_STRING_CONST(Color);
ZAF_DEFINE_STRING_CONST(ComboBox);
ZAF_DEFINE_STRING_CONST(Control);
ZAF_DEFINE_STRING_CONST(Ellipse);
ZAF_DEFINE_STRING_CONST(Frame);
ZAF_DEFINE_STRING_CONST(ImageBox);
ZAF_DEFINE_STRING_CONST(Label);
ZAF_DEFINE_STRING_CONST(ListBox);
ZAF_DEFINE_STRING_CONST(ListControl);
ZAF_DEFINE_STRING_CONST(Point);
ZAF_DEFINE_STRING_CONST(RadioButton);
ZAF_DEFINE_STRING_CONST(Rect);
ZAF_DEFINE_STRING_CONST(RoundedRect);
ZAF_DEFINE_STRING_CONST(ScrollableControl);
ZAF_DEFINE_STRING_CONST(ScrollBar);
ZAF_DEFINE_STRING_CONST(Size);
ZAF_DEFINE_STRING_CONST(SplitControl);
ZAF_DEFINE_STRING_CONST(TextBox);
ZAF_DEFINE_STRING_CONST(TextualControl);

}
}